<?php
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $config = $this->config()->get('config');
    $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();
  
  $this->layout()->breadcrumbs = false;
?>
<div class="searchHomeContent">
  <div class="row">
    <div class="home-image"></div>
  </div>
  <?php if ( $this->ils()->getOfflineMode() == "ils-offline"): ?>
    <div class="alert alert-warning">
      <h2><?=$this->transEsc('ils_offline_title')?></h2>
      <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
      <p><?=$this->transEsc('ils_offline_home_message')?></p>
      <?php $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
      <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
    </div>
  <?php endif; ?>
  <div class="row" style="position:relative;">
    <div class="text-center col-md-8 col-md-offset-2 well navbar" style="margin-bottom:-40px; position:relative; top: -40px;">

      <?php
          // Set default value if necessary:
          if (!isset($this->searchClassId)) {
              $this->searchClassId = 'Solr';
          }

          // Load search actions and settings (if any):
          $options = $this->searchOptions($this->searchClassId);
          $handlers = $this->searchbox()->getHandlers(
              $this->searchClassId,
              isset($this->searchIndex) ? $this->searchIndex : null
          );
          $handlerCount = count($handlers);
          $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
          $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
          $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
      ?>
      
      <form class="form-inline" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" id="searchForm" autocomplete="off">
        <div class="row">
          <div class="col-sm-7">
            <input class="form-control search-query<?php if($this->searchbox()->autocompleteEnabled($this->searchClassId)):?> autocomplete searcher:<?=$this->escapeHtml($this->searchClassId) ?><?php endif ?>" id="searchForm_lookfor" type="text" name="lookfor" value="<?=$this->escapeHtml($this->lookfor)?>" placeholder="<?=$this->transEsc("Start a new Basic Search")?>"/>
          </div>
          <?php if ($handlerCount > 1): ?>
            <div class="col-sm-3">
              <select id="searchForm_type" name="type" data-native-menu="false" class="form-control">
                <?php foreach ($handlers as $handler): ?>
                  <option value="<?=$this->escapeHtml($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
                <?php endforeach; ?>
              </select>
            </div>
          <?php elseif ($handlerCount == 1): ?>
            <input type="hidden" name="type" value="<?=$this->escapeHtml($handlers[0]['value'])?>" />
          <?php endif; ?>
          <div class="col-sm-2">
            <button type="submit" name="submit" class="btn btn-primary form-control" style="float:none; display:inline-block; margin-left:0;" value="<?=$this->transEsc("Find")?>"><i class="fa fa-search"></i> <?=$this->transEsc("Find")?></button>
          </div>
        </div>
          
        <?php
        /* Load hidden limit preference from Session */
        if (!empty($lastLimit)) {
          echo '<input type="hidden" name="limit" value="' . $this->escapeHtml($lastLimit) . '" />';
        }
        if (!empty($lastSort)) {
          echo '<input type="hidden" name="sort" value="' . $this->escapeHtml($lastSort) . '" />';
        }
        ?>
        
      </form>

    </div>
  </div>

<div class="row">
  <hr>
</div>

<?php $facetList = is_object($this->results) ? $this->results->getFacetList() : array(); ?>

<div class="row">

  <div class="col-md-6 well">
    <h4><i class="fa fa-home small"></i> <?=$this->translate('Participating libraries')?></h4>
    <ul class="list-unstyled">
      <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIE&quot;&filter[]=~building_dai_str_mv:&quot;DAIO&quot;&filter[]=~building_dai_str_mv:&quot;DAIZ&quot;">Berliner DAI-Bibliotheken (Eurasien, Orient, Zentrale)</a></li>
    </ul>
    <div class="row">
      <div class="col-md-6">
        <ul class="list-unstyled">
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIA&quot;"><?= $this->transEsc('DAIA') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIB&quot;"><?= $this->transEsc('DAIB') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAID&quot;"><?= $this->transEsc('DAID') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIE&quot;"><?= $this->transEsc('DAIE') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIF&quot;"><?= $this->transEsc('DAIF') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAII&quot;"><?= $this->transEsc('DAII') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIK&quot;"><?= $this->transEsc('DAIK') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIM&quot;"><?= $this->transEsc('DAIM') ?></a></li>
        </ul>
      </div>
      <div class="col-md-6">
        <ul class="list-unstyled">

          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIO&quot;"><?= $this->transEsc('DAIO') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIQ&quot;"><?= $this->transEsc('DAIQ') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIP&quot;"><?= $this->transEsc('DAIP') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIR&quot;"><?= $this->transEsc('DAIR') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIS&quot;"><?= $this->transEsc('DAIS') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIT&quot;"><?= $this->transEsc('DAIT') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DAIZ&quot;"><?= $this->transEsc('DAIZ') ?></a></li>
          <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;DEIA&quot;"><?= $this->transEsc('DEIA') ?></a></li>
        </ul>
      </div>
    </div>
    <ul class="list-unstyled">
      <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;BBSA&quot;"><?= $this->transEsc('BBSA') ?></a></li>
      <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;BWINCK&quot;"><?= $this->transEsc('BWINCK') ?></a></li>
      <li><a href="<?=$this->url('search-results')?>?filter[]=~building_dai_str_mv:&quot;BICUAZ&quot;"><?= $this->transEsc('BICUAZ') ?></a></li>
    </ul>
  </div>

  <div class="col-md-3">
    <div class="well">
      <h4><i class="fa fa-file small"></i> <?=$this->translate('Journals')?></h4>
      <ul class="list-unstyled">
        <li><a href="<?=$this->url('search-results')?>?lookfor=daizss8&amp;type=LocalNote"><?=$this->translate('DAI journals')?></a></li>
        <li><a href="<?=$this->url('search-results')?>?lookfor=a*gz04 OR argz06 OR argz04xx&amp;type=JournalNote"><?=$this->translate('Zenon journal holdings')?></a></li>
      </ul>
    </div>
    <div class="well">
      <div class="text-center">
        <small>
          <a  href="<?=$this->url('help-home')?>?topic=e_resources" data-lightbox target="_blank" class="help-link">
            <i class="fa fa-info-circle"></i> <?=$this->translate('information')?>
          </a>
        </small>
      </div>
      <h4>
        <i class="fa fa-globe small"></i> <?=$this->translate('e-publications')?> 
      </h4>


      <ul class="list-unstyled">
        <li>
            <a target="_blank" href="http://ezb.uni-regensburg.de/">
                <?=$this->translate('e-journals')?> <i class="fa fa-external-link"></i>
            </a>
        </li>
        <li><a href="<?=$this->url('search-results')?>?lookfor=ebook*&amp;type=LocalNote"><?=$this->translate('e-books')?></a></li>
        <li><a href="<?=$this->url('search-results')?>?lookfor=%22Online%20publication%22%20OR%20%22Online%20Publication%22%20OR%20%22online%20publication%22%20OR%20%22online%20Publication%22&type=LocalNote"><?=$this->translate('Online resources')?></a></li>
        <li>
            <a target="_blank" href="http://rzblx10.uni-regensburg.de/dbinfo/fachliste.php?bib_id=dai">
                <?=$this->translate('DBIS (Database Information System)')?> <i class="fa fa-external-link"></i>
            </a>
        </li>
      </ul>
    </div>
  </div>

  <div class="col-md-3 well">
    <h4><i class="fa fa-calendar small"></i> <?=$this->translate('Accessions')?></h4>
      <?php
      $start = new DateTime("now");
      $months = [];
      $accessionQueryGroups = [
          '🖵 eLibrary' => [
            'ebook',
            'ebookdai',
            'ebookfid',
            'ebooknl',
            'ebookoa',

            'ejournal',
            'ejournalal',
            'ejournaldai',
            'ejournalnl',
            'ejournalnk',
            'ejournaloa',

            'eartikel',
            'eartikeldai',
            'eartikeloa',

            'db',
            'dbfid',
            'dbnl',
            'dbnk',
            'dboa'
          ],
          'Athen' => ['a'],
          'Eurasien-Abteilung' => ['e'],
          'Istanbul' => ['i'],
          'KAAK Bonn' => ['k'],
          'Kairo' => ['c'],
          'Madrid' => ['m'],
          'Orient-Abteilung' => ['o'],
          'RGK Frankfurt' => ['f'],
          'Rom' => ['r'],
          'Zentrale Berlin' => ['za', 'zs']
      ];
      $additionalParameters = '&type=LocalNote';

      for ($i = 0; $i > -12; $i--){
          $dt = $this->dateTime()->monthShifter($start, $i);
          $queryMonth = $dt->format('my');

          $generalQueries = [];
          $librarySpecificQueries = [];
          foreach($accessionQueryGroups as $library => $prefixes) {
              $localQueries = [];
              foreach ($prefixes as $prefix) {
                  $generalQueries[] = $prefix . $queryMonth;
                  $localQueries[] = $prefix . $queryMonth;
              }
              $librarySpecificQueries[] =  [
                  'label' => $library,
                  'query' => join(' OR ', $localQueries).$additionalParameters
              ];
          }
          $generalQueries = array_unique($generalQueries);

          $months[] = [
              'date' => $dt,
              'generalQuery' => join(' OR ', $generalQueries).$additionalParameters,
              'specificQueries' => $librarySpecificQueries
          ];
      }
      ?>

          <ul class="list-unstyled" >
          <?php foreach (array_slice($months,0,12) as $month): ?>
              <li style="display:flex">
                  <div class="btn-group container">
                      <a href="<?=$this->url('search-results')?>?lookfor=<?=$month["generalQuery"]?>">
                          <?=$this->transEsc($month["date"]->format('F'))?> <?=$month["date"]->format('Y')?>
                      </a>
                      <a type="button" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <span class="caret"></span>
                          <span class="sr-only">Toggle Dropdown</span>
                      </a>
                      <ul class="dropdown-menu">
                          <?php foreach ($month['specificQueries'] as $specificQuery): ?>
                              <li><a href="<?=$this->url('search-results')?>?lookfor=<?= $specificQuery['query'] ?>"><?= $specificQuery['label'] ?></a></li>
                          <?php endforeach; ?>
                      </ul>
                  </div>
              </li>
          <?php endforeach; ?>
      </ul>
  </div>

</div>
    <?=$this->render('thesaurus/tree.phtml');?>
</div>

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
