<?php

  if (!isset($this->indexStart)) $this->indexStart = 0;
  $i = $this->indexStart;
?>

<h1><?=$this->transEsc('Cite this')?></h1>

<label for="format-select"><?=$this->transEsc('cite_choose_format')?>:</label>
<select id="format-select" class="form-control">
    <?php foreach ($this->citationFormats as $format ):  ?>
      <option onclick="showFormat('<?= $format ?>')"><?= $this->transEsc($format . ' Citation') ?></option>
    <?php endforeach; ?>
</select>

<p>
<div class="container">
<?php foreach ($this->results->getResults() as $current): ?>
  <div class="row" <?= ($i != 0) ? 'style="border-top: 1px solid #000;"' : '' ?>>
    <?php $recordNumber = $this->results->getStartRecord() + $i-$this->indexStart; ?>
    <?=$this->record($current)->getSearchResult('list-cite') ?>
  </div>
<?$i++ ?>
<?php endforeach; ?>
</div>


<script type="application/javascript">
  var activeFormat = 'APA';
  updateDisplayFormat();

  function showFormat(format) {
      activeFormat = format;
      updateDisplayFormat();
  }

  function updateDisplayFormat() {
      var allElements = document.getElementsByClassName('citation');
      var activeElements = document.getElementsByClassName('citation ' + activeFormat);

      var i;
      for(i = 0; i < allElements.length; i++){
          allElements[i].hidden = true;
      }
      for(i = 0; i < activeElements.length; i++){
          activeElements[i].hidden = false;
      }
  }
</script>
