<?php /* Display thumbnail if appropriate: */ ?>
<?php if ($cover): ?>
  <?php if ($this->link): ?><a href="<?=$this->escapeHtmlAttr($this->link)?>"><?php endif; ?>
  <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" style="max-width:120px;" src="<?=$this->escapeHtmlAttr($cover); ?>"/>
  <?php if ($this->link): ?></a><?php endif; ?>
<?php else: ?>
  <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
<?php endif; ?>
