<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->getUserObject();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [
          'holdings' => [],
          'electronic_holdings' => [],
          'total' => 0,
          'page' => 0,
          'itemLimit' => 0,
        ];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', compact('user')); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', array_map([$this, 'translate'], $holdings['blocks']))]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->recordLinker()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true" data-lightbox><?=$this->transEsc("hold_login")?></a>
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLinker()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true'])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); ?>
<?php if (!empty($holdingTitleHold)): ?>
  <a class="placehold icon-link" data-lightbox title="<?=$this->transEscAttr('request_place_text')?>" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holdingTitleHold))?>">
    <?=$this->icon('place-hold', 'icon-link__icon') ?>
    <span class="icon-link__label"><?=$this->transEsc('title_hold_place')?></span>
  </a>
<?php endif; ?>
<?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
  <?php if (!empty($urls)): ?>
    <?php foreach ($urls as $current): ?>
      <?php
        $url = $this->proxyUrl($current['url']);
                if(strcmp(substr($url, 0, 4 ), "wwww.") == 0) {
                    $url = "http://" . $url;
                }
                ?>
                <a  class="btn btn-block" role="button" href="<?= $url ?>" target="_blank"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <?php endforeach; ?>
  <?php endif; ?>
  <?php if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><?php endif; ?>
  <?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
<?php endif; ?>

<?php if (!empty($holdings['electronic_holdings'])): ?>
  <?=
    $this->context($this)->renderInContext(
        'RecordTab/holdingsils/electronic.phtml',
        ['holdings' => $holdings['electronic_holdings']]
    );
  ?>
<?php endif; ?>

<?php foreach ($holdings['holdings'] as $holding): ?>
    <?php $toggleTargetId = 'collapse' . str_replace([' ', '/'],'',$holding['location']); ?>
    <a  class="btn btn-zenon-default btn-block" role="button" data-toggle="collapse" href="#<?= $toggleTargetId; ?>" aria-expanded="false" aria-controls="collapse-group">
        <?php $locationText = $this->transEsc($holding['location']); ?>
        <?php if (isset($holding['locationhref']) && $holding['locationhref']): ?>
            <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
        <?php else: ?>
            <?= $locationText ?>
        <?php endif; ?>
    </a>

    <?php usort($holding['items'], function($a, $b) { return strcmp($a['summary'], $b['summary']); } ); ?>
    <div class="collapse" id="<?= $toggleTargetId; ?>">
        <table class="table table-striped" summary="<?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?>">
            <tr>
                <th><?=$this->transEsc("Call Number")?></th>
                <th><?= $this->transEsc("Located") ?></th>
                <th><?= $this->transEsc("holdings::Description") ?></th>
                <th><?= $this->transEsc("holdings::Item Status") ?></th>
                <th><?= $this->transEsc("holdings::Notes") ?></th>
            </tr>
            <?php foreach ($holding['items'] as $row): ?>
						    <?php
								$availabilityStatus = $row['availability'];
								$statusClass = $this->availabilityStatus()->getClass($availabilityStatus);
								?>
                <?php if (!(empty($row['callnumber']) && empty($row['summary']) &&  $this->transEsc($row['alt_summary']) && empty($row['status']) && empty($row['notes']))): ?>
                    <tr>
                        <td><?=$this->transEsc($row['callnumber'])?></td>
                        <td><?=$this->transEsc('holdings::' . $row['location_detail'])?></td>
                        <td>
                            <?php if (!empty($row['summary'])): ?>
                                <?= $this->transEsc($row['summary']) ?></td>
                            <?php else: ?>
                                <?= $this->transEsc($row['alt_summary']) ?>
                            <?php endif; ?>
                        </td>
                        <?php if ($row['lost_status'] == '1'): ?>
                            <td><?=$this->transEsc('holdings::item_status_missed') ?></td>
                        <?php else: ?>
                            <td><?=$this->transEsc('holdings::item_status_' . $availabilityStatus->getStatusDescription())?></td>
                        <?php endif; ?>
                        <td><?=$this->transEsc($row['notes'])?></td>
                    </tr>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </div>
<?php endforeach; ?>
<br/>
<?php $hostItem = $this->driver->tryMethod('getHostItemInformation'); ?>
<?php if($hostItem && $hostItem['id']): ?>
    <?php $ancestorHoldings = $this->recordLinker()->aggregateHostItemHoldings($hostItem['id']) ?>
    <?php if(!empty($ancestorHoldings['holdings'])): ?>
        <div class="alert">
            <h4 style="padding:15px" role="alert">
                <b>
                    <?php if (empty($holdings['holdings'])): ?>
                        <?=$this->translate("holdings::See parent record")?>:
                    <?php else: ?>
                        <?=$this->translate("holdings::See also parent record")?>:
                    <?php endif; ?>
                </b><br/>
                <small><?=$this->translate("holdings::See parent explanation")?></small>
            </h4>
        </div>
        <?php foreach ($ancestorHoldings['holdings'] as $holding): ?>
            <?php $toggleTargetId = 'collapse' . str_replace([' ', '/'], '', $holding['location'] . '_parent'); ?>
            <a  class="btn btn-zenon-default btn-block" role="button" data-toggle="collapse" href="#<?= $toggleTargetId; ?>" aria-expanded="false" aria-controls="collapse-group">
                <?php $locationText = $this->transEsc($holding['location']); ?>
                <?php if (isset($holding['locationhref']) && $holding['locationhref']): ?>
                    <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
                <?php else: ?>
                    <?= $locationText ?>
                <?php endif; ?>
            </a>

            <?php usort($holding['items'], function($a, $b) { return strcmp($a['summary'], $b['summary']); } ); ?>
            <div class="collapse" id="<?= $toggleTargetId; ?>">
                <table class="table table-striped" summary="<?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?>">
                    <tr>
                        <th><?=$this->transEsc("Call Number")?></th>
                        <th><?= $this->transEsc("Located") ?></th>
                        <th><?= $this->transEsc("holdings::Description") ?></th>
                        <th><?= $this->transEsc("holdings::Item Status") ?></th>
                        <th><?= $this->transEsc("holdings::Notes") ?></th>
                    </tr>
                    <?php foreach ($holding['items'] as $row): ?>
						            <?php
								        $availabilityStatus = $row['availability'];
								        $statusClass = $this->availabilityStatus()->getClass($availabilityStatus);
								        ?>
                        <?php if (!(empty($row['callnumber']) && empty($row['summary']) && empty($row['alt_summary']) && empty($row['status']) && empty($row['notes']))): ?>
                            <tr>
                                <td><?=$this->transEsc($row['callnumber'])?></td>
                                <td><?=$this->transEsc('holdings::' . $row['location_detail'])?></td>
                                <td>
                                <?php if (!empty($row['summary'])): ?>
                                    <?= $this->transEsc($row['summary']) ?></td>
                                <?php else: ?>
                                    <?= $this->transEsc($row['alt_summary']) ?>
                                <?php endif; ?>
                                </td>
                                <?php if ($row['lost_status'] == '1'): ?>
                                    <td><?=$this->transEsc('holdings::item_status_missed') ?></td>
                                <?php else: ?>
                                    <td><?=$this->transEsc('holdings::item_status_' . $availabilityStatus->getStatusDescription())?></td>
                                <?php endif; ?>
                                <td><?=$this->transEsc($row['notes'])?></td>
                            </tr>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </table>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>

<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
    <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
    <table class="table table-striped">
        <?php foreach ($history as $row): ?>
            <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
