<?php
    function trimSpecialCharacters($place) {
        return  preg_replace('/\W*$/', '', $place);
    }

    $marc = $this->driver->tryMethod('getMarcRecord');
    if (is_object($marc)) {
        $marcPhdField = $marc->getField('502');
    }
    $journalTitle = $this->driver->tryMethod('getContainerTitle');
    $formats = $this->driver->tryMethod('getFormats');
    if ($marcPhdField) {
        $format = 'thesis';
    } else if (!empty($journalTitle) || (is_array($formats) && in_array('Article', $formats))) {
        $format = 'article';
    } else {
        $format = 'book';
    }

    $zenonId = $this->driver->getUniqueId();
    $title = rtrim($this->driver->getShortTitle(), " /;.,:");
    $authors = $this->driver->tryMethod('getDeduplicatedAuthors')['primary']; // Todo: Andere Autoren auch in List aufnehmen
    $languages = $this->driver->tryMethod('getLanguages');
    $pubDates = $this->driver->tryMethod('getPublicationDates');
    $pubPlaces = $this->driver->tryMethod('getPlacesOfPublication');
    $pubNames = $this->driver->tryMethod('getPublishers');
    $pages = $this->driver->tryMethod('getPageRangeFromPhysicalDescription');
    $containers = $this->driver->tryMethod('getHostItemInformation');

    $result = array('id' => $zenonId);
    if($format){
      $result['type'] = $format;
    }
    if($title){
      $result['title'] = $title;
    }
    if($pubNames){
      $result['publisher'] = rtrim(implode('/', $pubNames), ',');
    }
    if($pubPlaces){
        $result['publisher-place'] = implode('/', array_map('trimSpecialCharacters', $pubPlaces));
    }
    if($pages){
        $result['pages'] = $pages;
    }
    if($containers){
        $result['container-title'] = trimSpecialCharacters($containers['label']);
    }

    if(!empty($authors)){
      $authorList = [];
      foreach($authors as $key => $value){
        $split = explode(',', $key);
        $author = ['family' => $split[0]];
        if(count($split) > 1){
          $author['given'] = trim($split[1]);
        }
        array_push($authorList, $author);
      }
      $result['author'] = $authorList;
    }

    if(!empty($pubDates)){
      $result['issued'] = ["raw" => implode('/', $pubDates)];
    }

    echo json_encode($result, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES);
