<h1>FAQ</h1>
<b>Haben Sie das gesuchte Buch oder einen Artikel nicht gefunden?</b> Überprüfen Sie zunächst Ihre Eingabe:<br>
<li>Sind Tippfehler in der Suchanfrage?<br></li>
<li>    Stehen die Suchbegriffe im richtigen Suchfeld?<br></li>
<li>    Ist der Suchbegriff richtig formuliert bzw. geschrieben? Die automatische Vervollständigung kann hilfreich sein.<br></li>
 <li>   Haben Sie versucht zu "trunkieren" (Wortstamm-Suche)?<br></li>
 <li>   Mit dem Trunkierungszeichen "*" ersetzen Sie beliebig viele Zeichen, mit dem Trunkierungszeichen "?" ersetzen Sie genau 1 Zeichen.<br></li>
 <li>   Haben Sie einen abgekürzten Vornamen eingegeben? Suchen Sie ohne den Vornamen und schränken Sie die Suche evtl. mit Hilfe anderer Suchkriterien ein (z.B. Wörter aus dem Titel).<br></li>
<br>
Führt auch dieser Weg nicht zum Ziel? Unter dem Link "Anfragen" können Sie <br>
<li>via E-Mail Ihre Fragen an uns richten.<br></li>
<li>einen Anschaffungsvorschlag machen.<br></li>
<li>Natürlich helfen Ihnen auch unsere Mitarbeiter an der Information gerne weiter.<br></li>
<br>
<b>Ich finde keine Signatur. Was nun?</b> Folgende Fälle sind möglich:<br>
<li> Es ist ein Online-Dokument. Bitte klicken Sie auf die URL.<br></li>
<li>Das Werk ist noch nicht im Bestand, sondern "bestellt", "In Bearbeitung", "im Geschäftsgang", "beim Buchbinder". In diesem Fall müssen Sie sich gedulden, bis das Werk in den Bestand aufgenommen ist, d.h. bis eine Signatur angezeigt wird.
<br></li>

<b>E-Book<br></b>
Ich habe über ZENON ein E-Book recherchiert, kann aber von zu Hause den Volltext nicht aufrufen. Woran liegt das?<br>
In ZENON sind die direkten Verlagslinks eingetragen. Noch erfolgt die Identifizierung anhand der bestehenden IP-Adresse, ob die Berechtigung für den Aufruf des Volltextes vorliegt. Sie müssen sich also innerhalb des DAI-Netzes befinden.<br>
<br>
<b>Warum kann ich beim Verlag xy das E-Book nicht herunterladen?</b><br>
Die E-Books können häufig zum persönlichen Gebrauch und zu Lehr- und Forschungszwecken gespeichert und ausgedruckt werden. Dies wird jedoch nicht von allen Verlagen zugelassen. Manche erlauben den Download einzelner Seiten, eines Kapitels oder aber des ganzen Dokumentes.
Bitte beachten Sie unbedingt die Nutzungs- und Lizenzbedingungen des jeweiligen Anbieters und die Copyrightbedingungen!<br>
E-Books dürfen weder elektronisch noch ausgedruckt an Dritte weitergegeben werden. Ein systematischer Download von kompletten E-Books oder großen Teilen davon, insbesondere durch Robots, ist untersagt.<br><br>

<b>Das Buch xy ist innerhalb des vom DAI lizenzierten Zeitraumes erschienen, es besteht jedoch kein Zugriff auf den Volltext. Was kann ich tun?</b><br>
Bitte schreiben Sie uns, wenn Sie einen solchen Titel finden. hier Verknüpfung zu elibrary@dainst.de<br><br>

<b>Wie kann ich auf die von der Bibliothek angebotenen E-Books zugreifen?</b><br>
Bei der Recherche in ZENON  finden Sie E-Books genauso wie herkömmliche Bücher. Wenn Sie gezielt nach E-Books recherchieren wollen, drücken Sie unter "E-Publikationen" auf den Button E-Books
Innerhalb des DAI führt Sie in der Einzeltrefferanzeige der Link im Feld "URL" direkt zum E-Book.<br>
Weitere Informationen zu E-Books erhalten Sie auf der Seite:..Unterseite<br>
<br>

<b>Was muss ich bei elektronischen Zeitschriften beachten?</b><br>
Elektronische Zeitschriften sind in ZENON und in der Elektronischen Zeitschriftenbibliothek verzeichnet.<br>
Die Suche in ZENON hat den Vorteil, dass Sie zugleich auch eventuell vorhandene Papierausgaben derselben Zeitschrift finden können. Im ZENON sind allerdings nur die für die einzelnen Abteilungen des DAI voll zugänglichen elektronischen Zeitschriften nachgewiesen, in der Elektronischen Zeitschriftenbibliothek auch die mit eingeschränktem Zugang. Hierbei wird Ihnen zumeist ein Inhaltsverzeichnis oder ein Abstract angeboten.
Bitte beachten Sie: In ZENON sind in der Volltrefferanzeige einer elektronischen Zeitschrift oftmals mehrere URLs angegeben. Bitte klicken Sie daher auf die prominent platzierte URL, der den bestmöglichen Zugang zu einer Zeitschrift bietet.
Ampel in der EZB Ansicht der EZB<br>
zum Vergrößern bitte anklicken<br>
Die Elektronische Zeitschriftenbibliothek bietet einen schnellen, strukturierten und einheitlichen Zugang zu wissenschaftlichen Volltextzeitschriften. Die Zugänglichkeit der einzelnen Zeitschriften wird über ein Ampelsystem geregelt.<br>
Bei Titeln, die für das gesamte DAI oder einzelne Abteilungen des DAI lizenziert sind - die also mit einem gelben Punkt gekennzeichnet sind - lesen Sie bitte das jeweilige "Readme", das Ihnen Hinweise zum Zugang zu den elektronischen Volltexten gibt. Lizenzierte Zeitschriften sind größtenteils nur aus dem Netz des DAI zugänglich.<br>
Weitere Informationen zu den Elektronischen Zeitschriften finden Sie unter Elektronische Medien. --> Seite anlegen u. Verknüpfung vornehmen<br>
Bei Fragen oder Zugangsproblemen wenden Sie sich bitte an das E-Journals-Team ---> elibrary@dainst.de hinterlegen<br>
<br>

<b>Was kann das Literaturverwaltungsprogramm Citavi?</b><br>
Siehe: Datenbanken - Hilfe - Citavi ---> Link auf Citavi-Seite einrichten, hier Beispiel: https://ub.fau.de/unser-service/literaturverwaltung/citavi/<br>
