<div>
    <ul class="nav nav-pills nav-justified">
        <li role="presentation" id="show-default-description" class="active"><a onclick="showDefaultDescription()"
                                                                                href="#">iDAI.bibliography</a></li>
        <li role="presentation" id="show-plus-description"><a href="#" onclick="showPlusDescription()">iDAI.bibliography
                PLUS</a></li>
    </ul>

    <div id="default-description">
        <h2 style="text-align: center; margin-top: 20px">iDAI.bibliography</h2>

        In iDAI.bibliography/ZENON finden Sie den Buch- und Zeitschriftenbestand der DAI-Bibliotheken inklusive Artikel
        aus Zeitschriften und Büchern, Rezensionen sowie Karten- und Archivmaterial, retrodigitalisierte Bücher und
        E-Books.

        <h3> Wie finde ich ein Buch oder einen Artikel in iDAI.bibliography/ZENON?</h3>
        <p>
            Sie können über das Suchfeld „Alle Felder“ beispielsweise den Verfasser und/oder Titel und/oder eindeutige
            Schlagwörter sowie Begriffe aus dem Volltext (elektronisch verfügbare Inhaltsverzeichnisse oder Medien)
            eingeben. Wenn Sie gezielt nach einem Verfasser suchen möchten, wählen Sie bitte das Suchfeld „Verfasser“
            aus. In der „Erweiterten Suche“ werden weitere Suchoptionen angeboten sowie die Möglichkeit, einzelne
            Suchbegriffe gezielt miteinander zu verknüpfen.
        </p>
        <p>
            Über die Funktion „Suche einschränken“ können Sie Ihre Rechercheergebnisse weiter spezifizieren und somit
            die Trefferliste nachträglich weiter einschränken.
        </p>

        <h3>Wie erkenne ich, an welchem Standort ein Buch/eine Zeitschrift vorhanden ist?</h3>
        <p>
            Klicken Sie auf das Suchergebnis, dann werden Ihnen sowohl die bestandführende Bibliothek/en als auch die
            Signatur/en angezeigt.
        </p>
        <p>
            Suchen Sie gezielt nach Medien einer bestimmten Bibliothek, können Sie Ihre Suchergebnisse entsprechend
            filtern („Suche einschränken“). Klicken Sie hierzu in der rechten Menüleiste auf die entsprechende
            Bibliothek. Nun
            werden Ihnen als Suchergebnis nur Medien aus dem Bestand dieser Bibliothek angezeigt.
        </p>

        <h3>Ich finde keine Signatur. Was nun?</h3>
        Folgende Fälle sind möglich:
        <ul>
            <li>Es ist ein Online-Dokument. Bitte klicken Sie auf die URL.</li>
            <li>Das Werk ist noch nicht im Bestand, sondern "bestellt", "In Bearbeitung", "im Geschäftsgang",
                "beim Buchbinder". In diesem Fall müssen Sie sich gedulden, bis das Werk in den Bestand aufgenommen ist,
                d.h. bis eine Signatur angezeigt wird.
            </li>
        </ul>

        <h3>Wie kann ich meine Suchergebnisse speichern?</h3>
        Sie können Ihre Suche als RSS-Feed abonnieren. So werden Sie über neue Literatur, die zu Ihren Suchbegriffen im
        Katalog verzeichnet wird, informiert. Darüber hinaus können Sie Ihre Suche als E-Mail versenden oder speichern
        (diese Funktion ist nur für angemeldete BenutzerInnen zugänglich).

        <h3>Wie kann ich meine Suchergebnisse speichern?</h3>
        Sie können Ihre Suche als RSS-Feed abonnieren. So werden Sie über neue Literatur, die zu Ihren Suchbegriffen im
        Katalog verzeichnet wird, informiert. Darüber hinaus können Sie Ihre Suche als E-Mail versenden oder speichern
        (diese Funktion ist nur für angemeldete BenutzerInnen zugänglich).

        <h3>Ich habe über iDAI.bibliography/ZENON ein E-Book/E-Journal recherchiert, kann aber von zu Hause den Volltext
            nicht aufrufen. Woran liegt das?</h3>
        Die Authentifizierung zur Nutzung der E-Books erfolgt aktuell über die IP-Adressen der DAI-Standorte. Sie müssen
        sich also innerhalb des DAI-Netzes befinden, um das E-Book zu lesen. Das gleiche gilt für kostenpflichtig
        E-Journals.

        <h3>Hinweis zu ProQuest Ebook Central</h3>
        Auch hier erfolgt die Authentifizierung über die IP-Adresse des DAI. ProQuest Ebook Central verlangt eine
        Anmeldung,
        d.h. eine E-Mail-Adresse + ein selbstgewähltes Passwort. Sofern man aus dem E-Book kopieren möchte oder ein
        Download
        vornimmt, muss ein Konto angelegt werden. Sofern man das E-Book online liest, muss kein Koto angelegt werden.

        <h3>Das Buch ist innerhalb des vom DAI lizenzierten Zeitraumes erschienen, es besteht jedoch kein Zugriff auf
            den
            Volltext. Was kann ich tun?</h3>
        Bitte schreiben Sie uns , wenn Sie einen solchen Titel finden. (elibrary@dainst.de)
    </div>
    <div id="plus-description" hidden>
        <h2 style="text-align: center; margin-top: 20px">iDAI.bibliography PLUS</h2>
        <p>
            Sobald Sie sich für eine Recherche im Bestand iDAI.bibliography PLUS entschieden haben, können Sie
            gleichzeitig
            im Titelbestand von iDAI.bibliography <strong>und</strong> weiteren ca. 11.000.000 bibliographischen
            Einträgen
            recherchieren. Darunter befinden sich beispielsweise die JSTOR-Artikel (<strong>Volltextzugriff auf dem
                DAI-Netz
                möglich</strong>), Artikel und Zeitschriftentitel aus den Nationallizenz-Paketen sowie lizenzfreie
            elektronische Ressourcen.
        </p>
        <p>Wir sind damit beschäftigt, den Bestand von iDAI.bibliography PLUS weiter aufzubereiten und auszubauen.
            Rückfragen senden Sie bitte gern an elibrary@dainst.de.
        </p>
    </div>

    <script src="/themes/archaeostrap/js/search-scopes-description.js"></script>
</div>
