<div class="row thesaurus" ng-app="zenonThs">

    <div ng-controller="ThsController" class="well col-md-12" ng-hide="columns.length < 1 || columns[0].length < 1">
        <h4>
            <i class="fa fa-inbox small"></i> <?=$this->translate('Thesaurus')?>
            <i ng-show="loading > 0" class="fa fa-spin fa-refresh" style="margin-left: 20px;"></i>
        </h4>

        <div style="overflow-x:hidden;">

            <div ng-style="{transform: 'translate(-'+offset+'px,0)'}"
                 style="transition: transform 0.5s; width:3000px;">
                <div ng-repeat="(colNo, column) in columns"
                     ng-style="{width: colWidth+'px'}"
                     style="height:380px; overflow:auto; display:inline-block; vertical-align:middle; padding-right:3px;">
                    <div class="list-group">
                        <a ng-click="loadColumn(colNo+1,entry)" style="cursor:pointer;" class="list-group-item" ng-class="{ active: active[colNo].id == entry.ths_id_str }" ng-repeat="entry in column">
                            <i ng-hide="entry.leaf" class="fa fa-chevron-right" style="float:right; margin-top:2px;"></i>
                            {{ entry.ths_heading_str }}
                        </a>
                    </div>
                </div>
                <div ng-show="active.length < 1"
                     ng-style="{width: colWidth*3+'px'}"
                     class="muted"
                     style="display:inline-block; text-align:center; vertical-align:middle;">
                    <i class="fa fa-arrow-left"></i>
                    <em><?=$this->transEsc("Select an entry to start a search for a thesaurus entry")?>.</em>
                </div>

            </div>

            <hr>

            <ul class="breadcrumb pull-left" style="margin:0; padding: 0 15px;">
                <li><strong><?=$this->transEsc("Selection")?>:</strong></li>
                <li ng-show="active.length < 1" class="muted"><em>-<?=$this->transEsc("No thesaurus entry selected")?>-</em></li>
                <li ng-repeat="(i,entry) in active">
                    {{entry.ths_heading_str}}
                    <span ng-hide="i >= active.length-1" class="divider"></span>
                </li>
            </ul>
            <div class="pull-right">
                <a ng-class="{disabled:(active.length < 1)}" ng-click="search(active[active.length-1])" class="btn btn-primary pull-right"><i class="fa fa-search"></i> <?=$this->transEsc("Find")?></a>
            </div>

        </div>

    </div>

    <?php $this->headScript()->appendFile("angular.min.js"); ?>
    <?php $this->headScript()->appendFile("thesaurus.js"); ?>

</div>
