<?php $account = $this->auth()->getManager(); ?>
<div class="navbar-header">
  <div style="padding-left:0px; position:relative">
      <div class="pull-left">
          <ul class="nav navbar-nav">
              <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      <img src="<?=$this->imageLink('kleinergreif.png') ?>"
                          style="height: 38px; margin-top: -16px; margin-bottom: -14px">
                      <b class="caret"></b>
                  </a>
                  <iframe class="dropdown-menu" src="https://idai.world/config/idai-nav.html"></iframe>
              </li>
          </ul>
      </div>
      <a href="<?=$this->url('search-home') ?>">
          <img class="pull-left" src="<?=$this->imageLink('logo_zenon.png') ?>" style="height: 36px; margin-top: 6px;">
      </a>
  </div>
</div>
<?php if ($this->layout()->searchbox !== false): ?>
  <section class="visible-lg">
    <?=$this->layout()->searchbox ?>
  </section>
<?php endif; ?>

<?php if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse" style="padding-right: 15px;">
    <nav>
      <ul class="nav navbar-nav navbar-right flip">
        <?php if ($this->layout()->searchbox == false): ?>
          <li>
              <a class="navbar-brand" href="<?=$this->url("search-advanced")?>"><?=$this->transEsc("Advanced Search")?></a>
          </li>
        <?php endif; ?>
        <li>
          <a class="navbar-brand" href="https://www.dainst.org/forschung/infrastruktur/bibliotheken" target="_blank"><?=$this->transEsc('Ask a Librarian')?> <i class="fa fa-external-link small"></i></a>
        </li>
        <?php if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <?php endif; ?>
        <?php $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
          </li>
        <?php endif; ?>
        <?php if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
          <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
            <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i class="fa fa-user"></i> <?=$this->transEsc("Your Account")?></a>
          </li>
          <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
            <a href="<?=$this->url('myresearch-logout')?>" class="modal-link" title="<?=$this->transEsc("Log Out")?>"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
          </li>
          <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
            <?php if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
            <?php else: ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" class="modal-link" title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
            <?php endif; ?>
          </li>
        <?php endif; ?>

        <?php if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
          <li class="dropdown">
            <form method="post" name="themeForm" id="themeForm">
              <input type="hidden" name="ui"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->layout()->themeOptions as $current): ?>
                <li<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>

        <?php if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="dropdown">
            <form method="post" name="langForm" id="langForm">
              <input type="hidden" name="mylang"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <?php foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
              <?php endforeach; ?>
            </ul>
          </li>
        <?php endif; ?>
      </ul>
    </nav>
  </div>
<?php endif; ?>
